[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "stream-processing-patterns"
version = "0.1.0"
description = "Lab de Engenharia de Dados e Performance com Python"
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "Leonardo Policarpo" },
]
dependencies = [
  "pandas",
  "streamlit",
  "psutil",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "black",
  "isort"
]
